version: '3'
services:
  bot:
    build: .
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.4"
    environment:
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
